### ISSUE TITLE
Update deislabs/cnab-go dependency to include BaseImage.OriginalImage

### ISSUE THREAD

**Issue by radu-matei** [docker/cnab-to-oci#39]
https://github.com/deislabs/cnab-go/pull/4 added a `OriginalImage` field for base images - I think we can use the already existing `annotations` field of the invocation image to store this.

Thoughts?

**Comment by silvin-lubecki** [comment]
Do we need this for the invocation image? I mean I thought it was a feature for component images, not invocation images. We already use annotation `io.cnab.component.original_name` for that, see  https://github.com/docker/cnab-to-oci/blame/master/README.md#L358
