### ISSUE TITLE
Configurable annotations for for the index

### ISSUE THREAD

**Issue by radu-matei** [docker/cnab-to-oci#40]
Looking at the raw index that this library generates, the first question I have is whether we can have support for configurable annotations - specifically, I'm looking at:

```
"io.docker.app.format": "cnab",
"io.docker.type": "app",
```

Does Docker App have a strong dependency on these two annotations?

Thanks!

**Comment by chris-crone** [comment]
> the first question I have is whether we can have support for configurable annotations

Yes, we should definitely add this.

> Does Docker App have a strong dependency on these two annotations?

I believe they're used by our registries but they shouldn't be hard coded here.

**Comment by radu-matei** [comment]
Nice, thanks a lot for the response, Chris.

Leaving this open so we can better track.
Thanks!
