### ISSUE TITLE
Forked containerd/containerd dependency

### ISSUE THREAD

**Issue by radu-matei** [docker/cnab-to-oci#41]
This library is using a forked version of `containerd/containerd`, and while upstream is at version 1.26, this is at 1.21, and I have a couple of questions:

- is there a plan for the changes in the fork to be pushed upstream?
- if that is taking longer, is there a plan to keep the branch used here up-to-date?

Thanks!

**Comment by silvin-lubecki** [comment]
Hello @radu-matei , as far as I remember, an upstream PR has been submitted here https://github.com/containerd/containerd/pull/3053
And yes you are right, I'll ping @simonferquel so he can update his fork 👍

**Comment by radu-matei** [comment]
Hey!
Any updates on the upstream PR?

**Comment by silvin-lubecki** [comment]
Unfortunately no, not yet 😞 We are pushing hard to get it merged!
