### ISSUE TITLE
Pushing the same bundle twice yields different digest

### ISSUE THREAD

**Issue by chris-crone** [docker/cnab-to-oci#43]
Pushing the same bundle twice without modification results in a different digest.

I suspect this is because of the image map which is unordered. To fix this, we’ll need to:
- use an ordered map (or list) when serialising
- document how the above works (likely in the CNAB spec) so that others can implement it too

**Comment by radu-matei** [comment]
Using canonical JSON ([as the spec specifies](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#the-bundlejson-file)) should probably fix this?

**Comment by chris-crone** [comment]
+1 on using canonical JSON wherever we can.

**Comment by silvin-lubecki** [comment]
Closed by #50
