### ISSUE TITLE
Handle bundle custome extensions

### ISSUE THREAD

**Issue by jeremyrickard** [docker/cnab-to-oci#45]
The cnab spec provides a mechanism for bundle authors to define [custom extensions](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#custom-extensions). It looks like cnab-to-oci currently does not handle these when a bundle is pushed, so this data would be lost on a pull. 

Porter plans on storing some things in the extensions and would like to see this persisted.

**Comment by silvin-lubecki** [comment]
Closed with #46
