### ISSUE TITLE
Push images if not present in registry

### ISSUE THREAD

**Issue by radu-matei** [docker/cnab-to-oci#67]
I've been going back and forth over this for the last couple of weeks - consider the following scenario - a bundle was just built locally, and the images have not been pushed - before calling `cnab-to-oci` to push the bundle, runtimes must first push the images to _a_ repository. Then, `cnab-to-oci` copies those images to a new repository, which is rather inefficient.

Do people have strong opinions against pushing images? I guess a sane workflow would be to checking if the image exists remotely and trying to copy (current behaviour), then fall back to tagging it accordingly and pushing it to the target repository.

Thoughts?

**Comment by squillace** [comment]
Wait, I'm not clear on the downside of... whatever it is that we are proposing to do here? an upsert push? What's the downside?

**Comment by eunomie** [comment]
I think #76 and #78 are fixing this issue, WDYT?
